### ISSUE TITLE
Only send as an Oregon sensor.

### ISSUE THREAD

**Issue by bongolf** [RouquinBlanc/ArduinOregon#1]
Hi!

I found this work of yours that seems to include just what I´m looking for, an Arduino library to send sensor data as an Oregon sensor. 
I´ve tried for a while now but I can't get it working (the last error is: "'BTHR918N' does not name a type")
Would it be possible for you to publish an easy example of just sending sensor data using the Oregon library?

**Comment by RouquinBlanc** [comment]
Hi Bongolf,

Did you put the content of the "libraries" folder into your Arduino's library folder (and perform a restart of the Arduino IDE)? It looks like the script is not finding the class BTHR918N which is defined in those files, which have to be in the Arduino path in order to be compiled.

Jonathan

**Comment by RouquinBlanc** [comment]
Ho, I just checked, and the BTHR918N was not merged on the original repo yet. Please use this instead: [fork of OWL-CM180](https://github.com/RouquinBlanc/OWL-CM180)
